### ISSUE TITLE
Execute same command and input in one device but browser get lower performance than command line

### ISSUE THREAD

**Issue by anhlevfx** [ffmpegjs/react-app#1]
Hello,

I tried your sample for reactjs and custom some function like scale and crop a .mp4 video. Tested on my Macbook pro 2015 and use same input video, same command. But I got very different render speed when use browser and command line.

On Chrome browser: 

> frame=   68 fps=3.3 q=28.0 size=       0kB time=00:00:02.78 bitrate=   0.1kbits/s speed=0.135x

    

On command line:

> frame=  554 fps= 52 q=28.0 size=    2560kB time=00:00:23.24 bitrate= 902.3kbits/ speed=2.26x

What should I do know to get higher render speed on browser? Thank you!

**Comment by jeromewu** [comment]
I think there is not much we can do for the speed issue as it is the nature of JavaScript. (If the command line version here means the C/C++ version)

**Comment by anhlevfx** [comment]
Hi,
ANH LE VU TUAN
Developer
mobile:  (+84) 327091223 <(+84)+327091223>
email:  tuananh25111995@gmail.com
address:  Ho Chi Minh City
<https://www.linkedin.com/in/anhlemultimedia/>


Vào CN, 26 thg 4, 2020 vào lúc 15:02 jeromewu <notifications@github.com>
đã viết:

**Comment by anhlevfx** [comment]
Hi,

Thank you your response! Yes, command line is C/C++ version installed on my
machine. I tried create a video editor web base local (use hardware user
for preview and render), but I think it's impossible because UX will not
good.

Regards,

ANH LE VU TUAN
Developer
mobile:  (+84) 327091223 <(+84)+327091223>
email:  tuananh25111995@gmail.com
address:  Ho Chi Minh City
<https://www.linkedin.com/in/anhlemultimedia/>


Vào CN, 26 thg 4, 2020 vào lúc 22:17 Vũ Tuấn Anh Lê <
tuananh25111995@gmail.com> đã viết:
