### ISSUE TITLE
NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope'

### ISSUE THREAD

**Issue by imack** [ffmpegjs/react-app#2]
Was getting this issue playing around with the main repo and used this test one to verify I wasn't doing anything wrong. I cloned this repo, `yarn`, `yarn start` and clicked "start" in chrome and got these errors:

![image](https://user-images.githubusercontent.com/492889/80674318-69876680-8a66-11ea-9e26-bcecae70d1ff.png)

```
739f13dd-9e2d-4084-84d6-e533dfdc9ec9:1 worker.js onmessage() captured an uncaught exception: NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://unpkg.com/@ffmpeg/core@v0.7.1/ffmpeg-core.js' failed to load.
threadPrintErr @ 739f13dd-9e2d-4084-84d6-e533dfdc9ec9:1
```

package.json is using the updated `"@ffmpeg/ffmpeg": "^0.8.1",`

**Comment by jeromewu** [comment]
Just tried and it works on my end, maybe it is the network issue.
BTW, I have deleted yarn.lock to prevent confusion as I am using npm only.
